#!/bin/bash
MYSQL_IDENTITY_RESOURCE_URL=${MYSQL_IDENTITY_RESOURCE_URL:-"https://ossrdbms-aad.database.windows.net"}
ENCODED_MYSQL_IDENTITY_RESOURCE_URL=$(jq -nr --arg url "$MYSQL_IDENTITY_RESOURCE_URL" '$url|@uri')
IDENTITY_URL="${IDENTITY_ENDPOINT}?api-version=${ENTRAID_API_VERSION}&resource=${ENCODED_MYSQL_IDENTIT>
ACCESS_TOKEN=$(curl -X GET "$IDENTITY_URL" -H "X-IDENTITY-HEADER: $IDENTITY_HEADER" | jq -r .access_to>
echo $ACCESS_TOKEN
